default: &default
  adapter: postgresql
  database: mmap-db
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: mmap-db
  pool: 5
  timeout: 5000
